### PR TITLE
feat: Allow custom format

### LINKED ISSUE #1: Set also filetime, if available
Thanks for writing this, I was just thinking how to unify all the files timestamps.

I am using `(release_timestamp>%Y-%m-%dT%H.%M.%S,upload_timestamp>%Y-%m-%dT%H.%M.%S,timestamp>%Y-%m-%dT%H.%M.%S,epoch>%Y-%m-%dT%H.%M.%S)s` for my output template and it seems the video download also sets mtime to a timestamp if possible, since it contains the time (of the tweet in my case).
It would be nice if this plugin could either use the output files timestamp as a lead or allow a similar pattern to specify the key(s) for using as mtime.

### PR DESCRIPTION
**Pull request by bradenhilton**
Fixes #1

Adds support for optionally specifying a custom format to parse the datetime.

@pke, would you be willing to test this? You can see the changes to the README to see how to use it.

### CODE REVIEW

**Comment by pke** [comment]
`--use-postprocessor FixupMtime` is actually all I need. Not sure how the format option comes into play for setting the filetime of the other files?

**Comment by bradenhilton** [comment]
This PR should fix the error you mentioned in #1 because it tries to guess the type and format of the mtime specified.

I'm not sure I understand what you mean by setting the filetime of other files. It already does set the mtime for most file types.

The updated README in this PR mentions some file types that are left untouched, I could see about supporting `*.PART*` files, but I do not plan on supporting `.dump` files unless yt-dlp is updated to provide a list of every single file that is output when downloading, which it currently does not do.

**Comment by bradenhilton** [comment]
Here's the result with the config and link you provided in https://github.com/bradenhilton/yt-dlp-FixupMtime/issues/1#issuecomment-1460503959:

```console
❯ yt-dlp -- https://twitter.com/eddie_1412/status/1633452798363705345
[twitter] Extracting URL: https://twitter.com/eddie_1412/status/1633452798363705345 
[twitter] 1633452798363705345: Downloading guest token 
[twitter] 1633452798363705345: Downloading JSON metadata 
[twitter] 1633452798363705345: Downloading m3u8 information 
[MetadataParser] Parsed meta_date from '%(release_year,upload_date).4s': '2023' 
[info] 1633451839831064582: Downloading 1 format(s): http-832 
[info] Writing video description to: 2023\2023-03-08T13.01.09-Eddie Graf - https：⧸⧸t.co⧸IQp5AGQmIj-twitter-1633451839831064582-624x344-00h02m00s.description 
[info] There's no subtitles for the requested languages 
[info] Downloading video thumbnail small ...
[info] Writing video thumbnail small to: 2023\2023-03-08T13.01.09-Eddie Graf - https：⧸⧸t.co⧸IQp5AGQmIj-twitter-1633451839831064582-624x344-00h02m00s.jpg 
[info] Writing video metadata as JSON to: 2023\2023-03-08T13.01.09-Eddie Graf - https：⧸⧸t.co⧸IQp5AGQmIj-twitter-1633451839831064582-624x344-00h02m00s.info.json 
[download] Destination: 2023\2023-03-08T13.01.09-Eddie Graf - https：⧸⧸t.co⧸IQp5AGQmIj-twitter-1633451839831064582-624x344-00h02m00s.mp4 
[download] 100% of    3.00MiB in 00:00:00 at 10.95MiB/s
[FixupMtime] Setting mtime of files to 2023-03-08T00:00:00 
[EmbedSubtitle] There aren't any subtitles to embed 
[Metadata] The info-json can only be attached to mkv/mka files
[Metadata] Adding metadata to "2023\2023-03-08T13.01.09-Eddie Graf - https：⧸⧸t.co⧸IQp5AGQmIj-twitter-1633451839831064582-624x344-00h02m00s.mp4"
[EmbedThumbnail] mutagen: Adding thumbnail to "2023\2023-03-08T13.01.09-Eddie Graf - https：⧸⧸t.co⧸IQp5AGQmIj-twitter-1633451839831064582-624x344-00h02m00s.mp4" 
[XAttrMetadata] Writing metadata to file's xattrs
```

```console
❯ Get-ChildItem . | Select-Object -Property LastWriteTime,Name

LastWriteTime       Name
-------------       ----
2023-03-08 00:00:00 2023-03-08T13.01.09-Eddie Graf - https：⧸⧸t.co⧸IQp5AGQmIj-twitter-1633451839831064582-624x344-00h02m00s.description
2023-03-08 00:00:00 2023-03-08T13.01.09-Eddie Graf - https：⧸⧸t.co⧸IQp5AGQmIj-twitter-1633451839831064582-624x344-00h02m00s.info.json
2023-03-08 00:00:00 2023-03-08T13.01.09-Eddie Graf - https：⧸⧸t.co⧸IQp5AGQmIj-twitter-1633451839831064582-624x344-00h02m00s.mp4
```

**Comment by pke** [comment]
Looks good to go for me! Thanks!

**Pull request merged**
